on: push
jobs:
  build-container:
    name: Build_container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
    - name: Login to docker hub
    - name: build and push to docker
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push to Docker hub
      uses: docker/build-push-action@v2.10.0
      with:
        context: .
        push: true
        tags: darovero/ghatest:latest, darovero/ghatest:${{ github.run_number }}